### ISSUE TITLE
JS开发和重构这样的分工是否正确，JS开发者还需要继续深入学习CSS吗？

### ISSUE THREAD

**Issue by icepy** [icepy/_posts#38]
> 讨论贴

前端工程师在公司中究竟该如何分工，一个人完成静态页面的制作和JS逻辑，还是将其分为 *JavaScript开发* 和 *页面重构*？

js开发者还需要去学习CSS吗？如果学习，该如何分配学习资源？

**Comment by icepy** [comment]
如果将前端开发定义为**软件工程**，对于*JavaScript*而言就不仅仅是一门小语言来对待，而是一门学科。往往有些时候（具体某些公司的业务需求而言），是否需要一个具备**软件工程**的前端开发者来掌舵。

1. 你需要具备良好的数学逻辑
2. 你需要具备良好的数据结构逻辑和算法知识
3. 你需要具备操作系统原理的知识
4. 你需要具备编译原理的知识
5. 你需要具备计算机系统体系的知识

那么**CSS**所具备的呢？

1. 排版布局的能力
2. 设置色彩字体的能力
3. 适配不同终端的能力
4. 处理动画的能力

可见从方向上来说，这完全是两个不同的知识体系，一个偏向**逻辑**，一个偏向**感性**，再加上公司业务的不同，我个人还是认为，将JS开发和重构分开会比较合理（至少在公司内的工作流程上），但是对于技能树而言，还是需要去学习CSS。

那么问题来了，究竟学习到什么程度？我个人的理解是：

1. 理解盒模型
2. 知道常见的布局方式
3. 知道一些常用的css3属性的使用方式
4. 会使用css3的动画

其它我偏向于有时间就分配学习资源，如果无时间，就还是会以JavaScript深入为主。

**Comment by icepy** [comment]
**为什么认为JS开发与重构分开的好**

首先 **分开** 的观点是立足于我们公司的业务形态而言的，我相信每一家公司的具体情况可能不同，如果说使用Node的公司应该会更需要具备**软件工程**的开发者，那么分开的目标也就达到了，每一个小组招募不同的人员，标准也会有所不同。

我们公司虽然是一家以粉丝经济为主的公司，但它的服务性质非常的突出，不仅对前端代码有着高标准的要求，对于开发协作方式也会有一定的要求。这也意味着从人的现实角度来说，同时具备**软件工程**思维和设计艺术感的同学，毕竟是少数，而这少数人还不一定能招募过来。为了更好的满足顺畅的工作流，我们渐渐的对于之前的工作流有所改变，将JS开发和重构慢慢的分离开，形成类似的流水线作业的方式，来出产Web应用。

这样的方式特别适合多产品线的公司，像我们公司的产品线都有N个，光直播类的我所知道的就有五六个产品。将这些分离开，会让各自的开发者在编程的角度上来说保持优势和互补，也可以在一定的框架基础上，快速的迭代更新。也许有同学会问：这样的方式岂不是对于个人的专业技术发展不利？我想说的是，公司的项目对于个人的成长还是占少部分的，大量的成长是个人的主动能动性。难道做完本职工作后，私人时间就不会去学习了么？对于别的项目组，你难道不会主动的去交流么？

**Comment by Yunfly** [comment]
en
