### ISSUE TITLE
跨专业学习前端，需要了解哪些基础知识，求推荐一些书籍？

### ISSUE THREAD

**Issue by 2ue** [icepy/_posts#40]
本人是非计算机专业毕业，对很多计算机的相关知识都不了解，目前已经开始从事前端这个行业。虽然目前基本能够很好的还原设计图，交互效果的实现。但是个人感觉在基础知识上还是很薄弱，这个在和同事的沟通讨论中可以明显看出，并且平时看某些框架的官方的文档和一些博客的技术文章也是比较吃力。比如前段时间，看一个sui框架，就对它里面提出的路由的概念很不理解，搜索出来的答案也是有些一头雾水；还有在自学AJAX这块也是对里面一些和后台交互的概念也很苦恼。鉴于这种情况，个人觉得需要好好的补一补相关的基础知识，但是又有点无从下手，请大神们提一些意见或者推荐一些实用的书籍。

PS:本人入行前端半年左右，还原效果图，JQ实现交互，实现兼容基本没问题。

**Comment by icepy** [comment]
@2ue 给我发一封邮件，为了提醒我不会忘记回复，邮件地址：xiangwenwe@foxmail.com 。如果现在回复你的话，我建议你阅读《JavaScript高级程序设计》，掌握了基础再去探索更深度的知识。路由系统是从服务端知识而来，准确的说它是从源到达目的地的时端到端的网路“规矩”，而这个“规矩”又遵从于HTTP对于资源的定义，所以说学习需要一个循环渐进的过程，你需要先掌握基础知识，才能走下一步。

问问自己：

- JS真的熟悉了么？
- HTTP熟悉了么
- CSS可以熟练的使用了么
